language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g bower grunt-cli
script:
  - git checkout build_dist_files
  - npm install
  - bower install
  - grunt
after_success:
  - sh -x ./publish.sh
branches:
  only: 
  - build_dist_files
